---
title: "Using RMarkdown and ggplot"
author: "Seungmo Kim"
date: "4/23/2017"
output: html_document
---

install.packages("tidyverse")
library(tidyverse)

mpg

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

#### 3.2.4 Exercises

# 1. Run ggplot(data = mpg) what do you see?
ggplot(data = mpg)
## I see no plot.

# 2. How many rows are in mtcars? How many columns?
nrow(mtcars)
ncol(mtcars)

# 3. What does the drv variable describe? Read the help for ?mpg to find out.
?mpg


# 4. Make a scatterplot of hwy vs cyl.


ggplot(data = mpg) + 
  geom_scatter(mapping = aes(x = cyl, y = hwy))
  
plot(data=mpg, x=cyl, y=hwy)
What happens if you make a scatterplot of class vs drv. Why is the plot not useful?

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
  
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
